### ISSUE TITLE
The user is able to start the game without filling a player name

### ISSUE THREAD

**Issue by bondrtait** [VelbazhdSoftwareLLC/Broker-1961-for-Android#47]
**Pre-conditions:**
Clear the game data on the device

**Steps:**
1. Run the game
2. Tap the Single Player Game button
3. Tap the ellipsis button
4. Tap New Game
5. Tick any two checkboxes on the right
6. Do not provide any names for the players
7. Tap Done

**Actual Result:**
The game is started. An empty player name is displayed at the top.

**Expected result:**
Som kind of validation error should prevent the user from initiating a game while player names are not populated
[Screen_recording_20240219_162158.webm](https://github.com/VelbazhdSoftwareLLC/Broker-1961-for-Android/assets/37595418/8320bc66-b16a-4b34-8b52-8c0e433c3a0a)

**Comment by bondrtait** [comment]
@TodorBalabanov This issue is still reproducible. Since the name is empty, there is no way to know which player is taking the turn at any given time.

**Comment by TodorBalabanov** [comment]
Thanks @bondrtait. We have decided not to fix this issue at this stage. It is not a fatal error, and we can live with it, at least in the current stage of development.
