### ISSUE TITLE
The user is unable to load a previously saved game

### ISSUE THREAD

**Issue by bondrtait** [VelbazhdSoftwareLLC/Broker-1961-for-Android#48]
**Pre-conditions:**
Create a save game and close the app

**Steps:**
1. Run the app
2. Tap the Single Player Game button
3. Tap the ellipsis button
4. Tap Load

**Actual Result:**
The app will either crash or redirect the user back to the main screen. 
The fatal exception produced when crashing:
`FATAL EXCEPTION: main
                                                                                                    Process: eu.veldsoft.broker, PID: 7308
                                                                                                    java.lang.RuntimeException: Unable to invoke no-args constructor for class eu.veldsoft.broker.model.Card. Registering an InstanceCreator with Gson for this type may fix this problem.`

**Expected result:**
The user should be able to load the previously saved game.

**Comment by bondrtait** [comment]
@TodorBalabanov The effect of this failure has changed - there is no exception now. However, the user is still unable to load a game. After tapping Load nothing happens at all.

**Comment by TodorBalabanov** [comment]
Thanks @bondrtait . The Load/Save functionality should be done as JSON serialization. This functionality is not written yet. I have just disabled the calls for the serialization. We will fix this issue in the future.
